n1 = input('Digite algo:')
print('O tipo primitivo é:', type(n1))
print('n1 é alfanumérico?', n1.isalnum())
print('n1 é alfabetico?', n1.isalpha())
print('n1 é código ASCII?', n1.isascii())
print('n1 é digito?', n1.isdigit())
print('n1 está em minúscula?', n1.islower())
print('n1 é decimal?', n1.isdecimal())
print('n1 é númerico?', n1.isnumeric())
print('n1 é imprimivel?', n1.isprintable())
print('n1 está em caixa alta?', n1.isupper())
print('n1 só tem espaços?', n1.isspace())
print('n1 está capitalizada?', n1.istitle())
